### PR TITLE
Update version of moment to fix nsp vulnerability 

### PR DESCRIPTION
**Pull request by PhilipGough**
ping @evanshortiss 

Hey, just a quick fix for the issue I created to update this security issue in the dependencies

### CODE REVIEW

**Comment by PhilipGough** [comment]
Retest this please

**Comment by evanshortiss** [comment]
Thanks @PhilipGough, seems to be failing CI. Does it pass `npm test` locally?

**Comment by PhilipGough** [comment]
@evanshortiss Hey sorry about that I didn't realise it failed. Yeah I can build with node 4 locally and it complains but the test pass anyway :) 
screen shot 2016-11-21 at 16 10 19

**Comment by evanshortiss** [comment]
@PhilipGough ok, I'll merge and take a look at travis. This module is old so might just be something to do with node 0.8/0.10 in the build.

**Comment by evanshortiss** [comment]
Thanks @PhilipGough

**Comment by PhilipGough** [comment]
Great thanks @evanshortiss

**Pull request merged**
